### ISSUE TITLE
[discovery] docker启动失败

### ISSUE THREAD

**Issue by yingzhuo** [yingzhuo/spring-cloud-microservice-example#2]
```
discovery_1  | 2016-09-17 08:54:21.104 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
discovery_1  |
discovery_1  | org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
discovery_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at example.discovery.ApplicationBoot.main(ApplicationBoot.java:12) [classes!/:na]
discovery_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
discovery_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
discovery_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
discovery_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
discovery_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
discovery_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
discovery_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:na]
discovery_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [app.jar:na]
discovery_1  | Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
discovery_1  | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:116) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:83) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:530) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:176) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	... 15 common frames omitted
discovery_1  | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:356) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:97) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
discovery_1  | 	... 20 common frames omitted
discovery_1  | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:791) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	... 22 common frames omitted
discovery_1  | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	... 24 common frames omitted
discovery_1  | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
discovery_1  | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
discovery_1  | 	... 26 common frames omitted
discovery_1  |
springcloudmicroserviceexample_discovery_1 exited with code 1
```

**Comment by yingzhuo** [comment]
错误地依赖了`servlet-api-2.5`

排除该依赖:

```
<!-- eureka -->
<dependency>
    <groupId>com.netflix.eureka</groupId>
    <artifactId>eureka-core</artifactId>
    <version>1.4.11</version>
    <exclusions>
        <exclusion>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.netflix.eureka</groupId>
    <artifactId>eureka-client</artifactId>
    <version>1.4.11</version>
</dependency>
```
